# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "freiraum.camp 2015"
email: "kontakt@freiraum.camp"
description: "Das freiraum.camp 2015 ist eine Begegnungsstätte für alle, die sich mit modernen Arbeitswelten beschäftigen (wollen)..."
baseurl: "/2015"
url: "http://freiraeume.github.io"

# Organizer Info
organizerName: "freiraum 2015"
organizerAlternateName: "freiraum.camp 2015"
organizerDescription: "Das freiraum.camp 2015 ist eine Begegnungsstätte für alle, die sich mit modernen Arbeitswelten beschäftigen (wollen)..."
organizerEmail: "kontakt@freiraum.camp"
organizerLink: "http://www.freiraum.camp/"

# Head
metaKeywords: "event, agile, lean, development, organisation, change, veränderung, augenhöen, intrinsify, hannover"
twitterAccount: "@freiraum"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Sessions"}
 - {permalink: "/speakers/", text: "Referenten"}
 - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "./schedule/", text: "Zur Agenda >>>"}
 - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}
rightNavigationButtons:
 - {link: "./schedule/", text: "Zur Agenda >>>"}
 - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}

# Hero Block
heroImage: "hannover.jpg"
heroTitle: "freiräume 2015 :: <typeout> "
eventDate: "29. & 30. Mai 2015, Hannover"
typeoutTextValues: '"", "Arbeiten auf Augenhöhe", "Neue Organisationsformen", "Alternativen zu Deiner Arbeitswelt", "Sammle Inspirationen", "Erkenne Chancen"'
typeoutFallback: "Auf zu neuen Arbeitswelten"
heroButtons:
 - {link: "./schedule/", text: "Die Agenda ist online!"}
 - {link: "http://de.amiando.com/ZDVKXIJ.html", text: "Ticket(s) kaufen"}

# About Block
aboutTitle: "Über das freiraum.camp 2015"
aboutBlock:
 - {title: "Konferenz", image: "conference.jpg", text: "Höre, welche Erfahrungen bisher gesammelt worden sind und hole Dir Anregungen für Deine Arbeitswelt!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "Teilnehmer", detail: "aus ganz Deutschland, Österreich und der Schweiz"}
 - {count: "20", specialCharacter: "+", info: "Stunden", detail: "Austausch über moderne Arbeitswelten"}
 - {count: "20", specialCharacter: "+", info: "Referenten", detail: "aus ganz Deutschland, Österreich und der Schweiz"}
 - {count: "17", specialCharacter: "+", info: "Sessions", detail: "zum Thema 'Neue Organisationsformen' und 'Neue Arbeitsweisen'"}

# Latest News Block
latestNewsTitle: "Neuigkeiten"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Rockstars der modernen Arbeitswelt"
rockstarSpeakersButtonText: "Wer spricht alles auf dem den freiräume.camp 2015?"

# Location Block
locationBlockTitle: "Wo?"
eventLocationName: "Haus der Wirtschaftsförderung"
eventLocationLink: "http://www.wirtschaftsfoerderung-hannover.de"
eventStreetAddress: "Vahrenwalder Str. 7"
eventAddressLocality: "Hannover"
eventAddressLocalityRegion: "Niedersachsen"
eventPostalCode: "30165"
eventAddressCountry: "Deutschland"
eventStartTime: "2015-05-29T09:30"
eventDoorTime: "09:00"
eventEndTime: "2015-10-30T17:00"
eventPlaceCoordinates: "52.386168, 9.733600"
mapCenterCoordinates: "52.386168, 9.733600"
mapMobileCenterCoordinates: "52.386168, 9.733600"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Was geht?"
twitterHashTag: "frrm15"

# Partners Block
#organizersTitle: "Organizers"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"

# Tickets Block
ticketsTitle: "Ticketpreis(e)"
ticketsInfo: "Mit dem Ticket kannst Du am freiräume.camp 2015 teilnehmen. Catering ist dabei inklusive. Das einzige, was Du selbst tragen musst, sind Deine Reisekosten ;)"
ticketsOffers:
 -
  name: "Frühbucher"
  price: "49,-"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  ribbon: "-25%"
  buyButtonLink: "http://de.amiando.com/ZDVKXIJ.html"
  buyButtonText: "Ausverkauft"
  validFrom: "2015-04-01T10:00"
  validThrough: "2015-04-30T23:59"
  disabled: true
 -
  name: "Normal"
  price: "65,-"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "http://de.amiando.com/ZDVKXIJ.html"
  buyButtonText: "Ticket(s) kaufen!"
  validFrom: "2015-05-01T10:00"
  validThrough: "2015-05-28T23:59"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=freiraumcamp", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/freiraumcamp-2015-Konferenz-und-Barcamp-f%C3%BCr-moderne-Arbeitswelten/1567028996917350", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Kontakt"
  links:
   - {link: "mailto:kontakt@freiraum.camp", text: "kontakt@freiraum.camp"}
 -
  title: "Weiteres"
  links:
   - {permalink: "/imprint/", text: "Impressum"}

# Blog
blogTitle: "Neuigkeiten"
blogCommentsEnabled: false
discusShortName: "freiraum"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Über uns"
aboutUs: "Wir haben die Erfahrung gemacht, dass der ausschließliche Fokus auf Prozesse Organisationen nicht unbedingt weiterbringt. Vielmehr bedarf es in den meisten Fällen einer signifikanten Veränderung der Arbeitskultur & -welt der von der Veränderung betroffenen Personen. Wir möchten euch mit dieser Veranstaltung zu einem gemeinsamen Lernen aus bisherigen Erfahrungen und einem Dialog darüber einladen. Ihr habt damit die Gelegenheit, aus dieser Veranstaltung neue Ideen und Inspirationen für eure Arbeitswelt mitzunehmen."
